spring:
  application:
    name: gongsi-analyzer
  profiles:
    include: secret
  # PostgreSQL DB 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: gncn0301
    driver-class-name: org.postgresql.Driver
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  # 기본적으로 응답할 미디어 타입을 application/json으로 설정
  default-produces-media-type: application/json
  # API 문서에 포함시킬 경로 설정. /api/로 시작하는 모든 경로를 포함
  paths-to-match:
    - /api/**
  # Swagger UI 페이지의 경로를 /swagger-ui.html로 설정 (기본값)
  swagger-ui:
    path: /swagger-ui.html
  # API 문서(JSON)의 경로를 /api-docs로 설정
  api-docs:
    path: /api-docs

  # API 기본 정보 설정 (Swagger UI 상단에 표시됨)
  info:
    title: "공시 분석기 (Gongsi Analyzer) API"
    description: "DART 공시 데이터를 인덱싱하고 검색하는 기능을 제공하는 API 문서입니다."
    version: "v1.0.0"

  # API 서버 정보 설정
  servers:
    - url: http://localhost:8080
      description: 로컬 개발 서버